# TIL IaC - Workflow
# Description: This pipeline build and deploy the infrastructure for the TIL IaC Demo project
name: CI

# Controls when the workflow will run
on:
    workflow_dispatch:
    push:
      branches:
          - main
          - feature/*
      paths:
          - 'bicep/projects/deploymentstacks/**'
          - '.github/workflows/iac-til-iac-workflow.yml'

permissions:
    id-token: write 
    contents: read

  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  release:
    needs: build
    environment: stack
    runs-on: self-hosted
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run az commands'
        run: |
          az account show
          az group list
