# TIL IaC - Workflow
# Description: This pipeline build and deploy the infrastructure for the TIL IaC Demo project
name: til-iac-workflow.yml

# Controls when the workflow will run
on:
    workflow_dispatch:
    push:
      branches:
          - main
          - feature/*
      paths:
          - 'bicep/projects/deploymentstacks/**'
          - '.github/workflows/iac-til-iac-workflow.yml'

permissions:
    id-token: write 
    contents: read

  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  release:
    # needs: build
    environment: stack
    runs-on: self-hosted
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run az commands'
        run: |
          az account show
          az group list
