# TIL IaC - Workflow
# Description: This pipeline build and deploy the infrastructure for the TIL IaC Demo project
name: til-iac-workflow-2

# Controls when the workflow will run
on:
    push:
      branches:
          - main
          - feature/*
      # paths:
      #     - 'bicep/projects/deploymentstacks/**'
      #     - '.github/workflows/iac-til-iac-workflow.yml'
    workflow_dispatch:
permissions:
    id-token: write 
    contents: read

  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build:
  #   uses: .github/workflows/iac-ci-template.yml
  #   with:
  #     environment: de
  #     location: centralindia
  #     project: stack
  #     projectFolder: deploymentstacks
  #   secrets:
  #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
  release:
    # needs: build
    environment: stack
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: action/checkout@v3

      - name: 'Run az commands'
        run: |
          az account show
          az group list
